<?php

return [
    'home' => 'site/home',
    'forgot' => 'site/forgot',
    'admin-posts' => 'admin/admin-posts/index',
    'create-admin-posts' => 'admin/admin-posts/create',
    'update-admin-posts/<id:\d+>' => 'admin/admin-posts/update',
    'view-admin-posts/<id:\d+>' => 'admin/admin-posts/view',
    'change-password' => 'admin/employee/change-password',
    'employee' => 'admin/employee/index',
    'create-employee' => 'admin/employee/create',
    'update-employee/<id:\d+>' => 'admin/employee/update',
    'view-employee/<id:\d+>' => 'admin/employee/view',
    'branch' => 'admin/branch/index',
    'create-branch' => 'admin/branch/create',
    'update-branch/<id:\d+>' => 'admin/branch/update',
    'view-branch/<id:\d+>' => 'admin/branch/view',
    'uploads-file' => 'appointment/uploads/index',
    'appointment' => 'appointment/appointment/index',
    'create-appointment' => 'appointment/appointment/create',
    'update-appointment/<id:\d+>' => 'appointment/appointment/update',
    'view-appointment/<id:\d+>' => 'appointment/appointment/view',
    'estimated-proforma/<id:\d+>' => 'appointment/estimated-proforma/add',
    'sub-services/<id:\d+>' => 'appointment/sub-services/add',
    'close-estimate/<id:\d+>' => 'appointment/close-estimate/add',
    'sub-services/<id:\d+>' => 'appointment/close-estimate-sub-service/add',
    'port-call-data/<id:\d+>' => 'appointment/port-call-data/update',
];
